import { useState } from 'react'
import axios from 'axios'

// LLM-authored Sigma rule → human review → push to Wazuh. Works from an L1
// incident (incidentId) or an L2 anomaly finding (nodeId). Human-in-the-loop by
// design: the analyst edits the YAML before it is delivered to the SIEM. This is
// an integration claim — the rule is delivered and accepted, not a detection claim.

const FONT = 'var(--font-ui)'

export default function SigmaGenerator({ incidentId, nodeId }: { incidentId?: string; nodeId?: string }) {
    const [provider, setProvider] = useState('groq')
    const [premium, setPremium] = useState(false)
    const [generating, setGenerating] = useState(false)
    const [sigma, setSigma] = useState<string | null>(null)
    const [meta, setMeta] = useState('')
    const [pushing, setPushing] = useState(false)
    const [msg, setMsg] = useState<string | null>(null)

    const generate = async () => {
        setGenerating(true); setMsg(null); setSigma(null)
        try {
            const body: Record<string, unknown> = { provider, premium }
            if (incidentId) body.incident_id = incidentId
            if (nodeId) body.node_id = nodeId
            const { data } = await axios.post('/api/wazuh/generate-sigma', body)
            setSigma(data.sigma_yaml)
            setMeta(`${data.model}${data.premium ? ' ★' : ''}`)
        } catch (e: any) {
            setMsg(`✗ Generation failed — ${e?.response?.data?.detail || 'see logs'}`)
        } finally { setGenerating(false) }
    }

    const push = async () => {
        if (!sigma) return
        setPushing(true); setMsg(null)
        try {
            const { data } = await axios.post('/api/wazuh/export-rule', { sigma })
            setMsg(data.ok
                ? `✓ Rule ${data.rule_id} delivered to Wazuh — ${data.filename}`
                : `✗ Wazuh rejected the rule (HTTP ${data.put_status})`)
        } catch {
            setMsg('✗ Export failed — is the Wazuh manager running?')
        } finally { setPushing(false) }
    }

    const btn = (bg: string, fg: string, border: string): React.CSSProperties => ({
        padding: '6px 14px', background: bg, border, color: fg, fontFamily: FONT,
        fontSize: 11, fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.05em', cursor: 'pointer',
    })

    return (
        <div>
            <div style={{ display: 'flex', alignItems: 'center', gap: 8, flexWrap: 'wrap' }}>
                <select value={provider} onChange={e => setProvider(e.target.value)}
                    style={{ fontFamily: FONT, fontSize: 11, padding: '5px 8px', background: 'var(--bg-card)', color: 'var(--text-primary)', border: '1px solid var(--border-light)' }}>
                    <option value="gemini">Gemini</option>
                    <option value="groq">Groq (Llama)</option>
                    <option value="anthropic">Claude</option>
                    <option value="openai">OpenAI (GPT)</option>
                </select>
                <label style={{ fontFamily: FONT, fontSize: 11, color: 'var(--text-muted)', display: 'flex', alignItems: 'center', gap: 4, cursor: 'pointer' }}>
                    <input type="checkbox" checked={premium} onChange={e => setPremium(e.target.checked)} /> ★ premium
                </label>
                <button onClick={generate} disabled={generating}
                    style={{ ...btn('transparent', 'var(--accent-primary)', '2px solid var(--accent-primary)'), opacity: generating ? 0.6 : 1, cursor: generating ? 'wait' : 'pointer' }}>
                    {generating ? 'Generating…' : 'Generate Sigma (LLM)'}
                </button>
            </div>
            {sigma !== null && (
                <div style={{ marginTop: 10 }}>
                    <div style={{ fontFamily: FONT, fontSize: 10, color: 'var(--text-muted)', marginBottom: 4 }}>
                        generated by {meta} — review/edit before pushing
                    </div>
                    <textarea value={sigma} onChange={e => setSigma(e.target.value)} spellCheck={false} rows={12}
                        style={{
                            width: '100%', boxSizing: 'border-box', fontFamily: 'var(--font-mono, monospace)', fontSize: 11,
                            background: 'var(--bg-card)', color: 'var(--text-primary)', border: '1px solid var(--border-light)', padding: 8, resize: 'vertical',
                        }} />
                    <button onClick={push} disabled={pushing}
                        style={{ ...btn('var(--accent-primary)', '#fff', 'none'), marginTop: 6, opacity: pushing ? 0.6 : 1, cursor: pushing ? 'wait' : 'pointer' }}>
                        {pushing ? 'Pushing…' : 'Push generated rule to SIEM'}
                    </button>
                </div>
            )}
            {msg && (
                <div style={{ marginTop: 8, fontFamily: FONT, fontSize: 11, color: msg.startsWith('✓') ? 'var(--status-good, #16a34a)' : 'var(--status-critical, #dc2626)' }}>{msg}</div>
            )}
        </div>
    )
}
